### ISSUE TITLE
Integrate new design elements from Fury/Wrapbootstap template

### ISSUE THREAD

**Issue by otech47** [blockchainedu/ben-website#17]
Started this repo (https://github.com/blockchainedu/benweb/issues) for the redesign @Jinglan has been working on and tracking issues there

**Comment by alinalebron** [comment]
@otech47 @Jinglan when was this new repo discussed and why not implement the changes here to keep everything aligned with goals?

**Comment by otech47** [comment]
Finished here https://github.com/blockchainedu/benweb 

Just need to [port](https://github.com/blockchainedu/ben-website/issues/24) to unify the repos

N
