### ISSUE TITLE
Explore deploying a MySQL instance on Upcloud

### ISSUE THREAD

**Issue by otech47** [blockchainedu/ben-website#23]
@agarwalakarsh If you could dig up the pricing as well so we'd know how many months the credits will last with a basic database instance. I think the lowest compute available should suffice I don't expect many read/writes to be needed until maybe after some more functionality is developed

Backup option if this proves to be troublesome is an AWS free tier account that will last 1 year

**Comment by agarwalakarsh** [comment]
Sure. @otech47, that helps. I'll attach the pricing page here, once I have something online.

**Comment by agarwalakarsh** [comment]
I think going with AWS is a better option. As UpCloud's $500 credits are valid for 45 days. And there after it is chargeable on a per month basis, starting from $5 / mo.

Whereas, with AWS Free Tier, we can get a MySQL Instance for free with 1 CPU core and 1 GB Memory for the whole year, running 365*24*7.

Hence, I think going ahead with AWS is more viable in the long run as opposed to UpCloud. Also, if we think that MySQL is getting heavy, we can always extract the data and store it in S3 Bucket (5 GB in the free tier).

**Comment by otech47** [comment]
Ok great thanks for doing the research! I think we can close this out for now knowing AWS is our move. Since we won't need to use the database immediately let's put this on pause until we have a database schema ready to deploy so we can maximize the 1 year free tier. We'll track that in a separate issue.
